# Generated by Django 5.0.14 on 2025-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_company_name_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Địa chỉ công ty', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_registration_document',
            field=models.FileField(blank=True, help_text='Giấy đăng ký doanh nghiệp', null=True, upload_to='business_registrations/'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True, help_text='Mô tả công ty', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Email công ty', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_activity',
            field=models.CharField(blank=True, help_text='Lĩnh vực hoạt động', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scale',
            field=models.CharField(blank=True, help_text='Quy mô công ty', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Mã số thuế', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Website công ty', null=True),
        ),
    ]
