# Generated by Django 5.0.14 on 2025-11-24 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(help_text="CV file (PDF/DOCX)", upload_to="cvs/"),
                ),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCREENING", "Screening"),
                            ("INTERVIEW", "Interview"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True, help_text="AI score 0-100", null=True
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True, help_text="AI analysis result", null=True
                    ),
                ),
                ("screener_notes", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("PHONE", "Phone"),
                            ("VIDEO", "Video"),
                            ("ONSITE", "On-site"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "db_table": "interviews",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewPanel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("MEMBER", "Member"),
                            ("OBSERVER", "Observer"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "score",
                    models.FloatField(blank=True, help_text="Score 0-100", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panels",
                        to="applications.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview_panels",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[("OFFER", "Offer"), ("REJECT", "Reject")],
                        max_length=20,
                    ),
                ),
                (
                    "offer_letter_file",
                    models.FileField(blank=True, null=True, upload_to="offer_letters/"),
                ),
                ("salary", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="applications.application",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decided_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_results",
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "status"], name="application_job_id_606b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate"], name="application_candida_0452de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="application_status_e61111_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["ai_score"], name="application_ai_scor_5e1a74_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "candidate")},
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["scheduled_at", "status"], name="interviews_schedul_16ce97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["application"], name="interviews_applica_5d9c27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewpanel",
            index=models.Index(
                fields=["interview"], name="interview_p_intervi_915fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewpanel",
            index=models.Index(
                fields=["interviewer"], name="interview_p_intervi_405e85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interviewpanel",
            unique_together={("interview", "interviewer")},
        ),
        migrations.AddIndex(
            model_name="recruitmentresult",
            index=models.Index(
                fields=["application"], name="recruitment_applica_d7940d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruitmentresult",
            index=models.Index(
                fields=["decided_by"], name="recruitment_decided_76bcf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruitmentresult",
            index=models.Index(
                fields=["decided_at"], name="recruitment_decided_6a6d74_idx"
            ),
        ),
    ]
