# Generated by Django 5.0.14 on 2025-11-24 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField(help_text="Job Description (JD)")),
                ("salary", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULLTIME", "Full-time"),
                            ("PARTTIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERN", "Intern"),
                        ],
                        default="FULLTIME",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="jobs_status_92f544_idx"),
                    models.Index(fields=["deadline"], name="jobs_deadlin_0e940b_idx"),
                    models.Index(fields=["created_by"], name="jobs_created_ab83fb_idx"),
                ],
            },
        ),
    ]
