# Generated by Django 5.0.14 on 2025-11-27 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Số năm kinh nghiệm yêu cầu', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='positions_count',
            field=models.IntegerField(default=1, help_text='Số lượng vị trí cần tuyển'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='RecruitmentProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tên quy trình', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='recruitment_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.recruitmentprocess'),
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('SCREENING', 'Sàng lọc hồ sơ'), ('PHONE_INTERVIEW', 'Phỏng vấn điện thoại'), ('TECHNICAL_TEST', 'Bài test kỹ thuật'), ('INTERVIEW', 'Phỏng vấn'), ('FINAL_INTERVIEW', 'Phỏng vấn cuối'), ('OFFER', 'Gửi offer'), ('ONBOARDING', 'Onboarding')], max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(default=7, help_text='Thời gian dự kiến (ngày)')),
                ('is_required', models.BooleanField(default=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobs.recruitmentprocess')),
            ],
            options={
                'db_table': 'process_steps',
                'ordering': ['order'],
                'unique_together': {('process', 'order')},
            },
        ),
    ]
